from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_telaPrincipal(object):
    def setupUi(self, telaPrincipal):
        telaPrincipal.setObjectName("telaPrincipal")
        telaPrincipal.resize(908, 442)
        self.centralwidget = QtWidgets.QWidget(telaPrincipal)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setStyleSheet("QFrame{\n"
"background-color: rgb(248, 248, 248);\n"
"}")
        self.frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.frame)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setSpacing(0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.frame_4 = QtWidgets.QFrame(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_4.sizePolicy().hasHeightForWidth())
        self.frame_4.setSizePolicy(sizePolicy)
        self.frame_4.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.frame_4)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setSpacing(0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.frame_3 = QtWidgets.QFrame(self.frame_4)
        self.frame_3.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_3.sizePolicy().hasHeightForWidth())
        self.frame_3.setSizePolicy(sizePolicy)
        self.frame_3.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.frame_3)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setSpacing(0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.toolButton_16 = QtWidgets.QToolButton(self.frame_3)
        self.toolButton_16.setMinimumSize(QtCore.QSize(80, 80))
        self.toolButton_16.setMaximumSize(QtCore.QSize(80, 80))
        self.toolButton_16.setText("")
        self.toolButton_16.setObjectName("toolButton_16")
        self.horizontalLayout_4.addWidget(self.toolButton_16)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem)
        self.toolButton_13 = QtWidgets.QToolButton(self.frame_3)
        self.toolButton_13.setMinimumSize(QtCore.QSize(80, 80))
        self.toolButton_13.setMaximumSize(QtCore.QSize(80, 80))
        self.toolButton_13.setText("")
        self.toolButton_13.setObjectName("toolButton_13")
        self.horizontalLayout_4.addWidget(self.toolButton_13)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem1)
        self.toolButton_14 = QtWidgets.QToolButton(self.frame_3)
        self.toolButton_14.setMinimumSize(QtCore.QSize(80, 80))
        self.toolButton_14.setMaximumSize(QtCore.QSize(80, 80))
        self.toolButton_14.setText("")
        self.toolButton_14.setObjectName("toolButton_14")
        self.horizontalLayout_4.addWidget(self.toolButton_14)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem2)
        self.gridLayout_3.addWidget(self.frame_3, 1, 1, 1, 1)
        self.frame_6 = QtWidgets.QFrame(self.frame_4)
        self.frame_6.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_6.sizePolicy().hasHeightForWidth())
        self.frame_6.setSizePolicy(sizePolicy)
        self.frame_6.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame_6)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem3)
        self.toolButton_10 = QtWidgets.QToolButton(self.frame_6)
        self.toolButton_10.setMinimumSize(QtCore.QSize(80, 80))
        self.toolButton_10.setMaximumSize(QtCore.QSize(80, 80))
        self.toolButton_10.setText("")
        self.toolButton_10.setObjectName("toolButton_10")
        self.horizontalLayout_3.addWidget(self.toolButton_10)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem4)
        self.toolButton_11 = QtWidgets.QToolButton(self.frame_6)
        self.toolButton_11.setMinimumSize(QtCore.QSize(80, 80))
        self.toolButton_11.setMaximumSize(QtCore.QSize(80, 80))
        self.toolButton_11.setText("")
        self.toolButton_11.setObjectName("toolButton_11")
        self.horizontalLayout_3.addWidget(self.toolButton_11)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem5)
        self.toolButton_12 = QtWidgets.QToolButton(self.frame_6)
        self.toolButton_12.setMinimumSize(QtCore.QSize(80, 80))
        self.toolButton_12.setMaximumSize(QtCore.QSize(80, 80))
        self.toolButton_12.setText("")
        self.toolButton_12.setObjectName("toolButton_12")
        self.horizontalLayout_3.addWidget(self.toolButton_12)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem6)
        self.toolButton_17 = QtWidgets.QToolButton(self.frame_6)
        self.toolButton_17.setMinimumSize(QtCore.QSize(80, 80))
        self.toolButton_17.setMaximumSize(QtCore.QSize(80, 80))
        self.toolButton_17.setText("")
        self.toolButton_17.setObjectName("toolButton_17")
        self.horizontalLayout_3.addWidget(self.toolButton_17)
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem7)
        self.toolButton_18 = QtWidgets.QToolButton(self.frame_6)
        self.toolButton_18.setMinimumSize(QtCore.QSize(80, 80))
        self.toolButton_18.setMaximumSize(QtCore.QSize(80, 80))
        self.toolButton_18.setText("")
        self.toolButton_18.setObjectName("toolButton_18")
        self.horizontalLayout_3.addWidget(self.toolButton_18)
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem8)
        self.gridLayout_3.addWidget(self.frame_6, 1, 0, 1, 1)
        self.frame_2 = QtWidgets.QFrame(self.frame_4)
        self.frame_2.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_2.sizePolicy().hasHeightForWidth())
        self.frame_2.setSizePolicy(sizePolicy)
        self.frame_2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.frame_2)
        self.gridLayout_6.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_6.setSpacing(0)
        self.gridLayout_6.setObjectName("gridLayout_6")
        spacerItem9 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_6.addItem(spacerItem9, 4, 5, 1, 1)
        spacerItem10 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_6.addItem(spacerItem10, 1, 2, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.frame_2)
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.gridLayout_6.addWidget(self.label_2, 3, 2, 1, 1, QtCore.Qt.AlignHCenter)
        self.BTN_GERAR_RELATORIO = QtWidgets.QToolButton(self.frame_2)
        self.BTN_GERAR_RELATORIO.setMinimumSize(QtCore.QSize(80, 80))
        self.BTN_GERAR_RELATORIO.setMaximumSize(QtCore.QSize(80, 80))
        self.BTN_GERAR_RELATORIO.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icons/iconPDF.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.BTN_GERAR_RELATORIO.setIcon(icon)
        self.BTN_GERAR_RELATORIO.setIconSize(QtCore.QSize(70, 70))
        self.BTN_GERAR_RELATORIO.setObjectName("BTN_GERAR_RELATORIO")
        self.gridLayout_6.addWidget(self.BTN_GERAR_RELATORIO, 1, 1, 1, 1)
        self.label = QtWidgets.QLabel(self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setObjectName("label")
        self.gridLayout_6.addWidget(self.label, 3, 1, 1, 1, QtCore.Qt.AlignHCenter)
        self.label_4 = QtWidgets.QLabel(self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        self.label_4.setObjectName("label_4")
        self.gridLayout_6.addWidget(self.label_4, 3, 3, 1, 1, QtCore.Qt.AlignHCenter)
        self.toolButton_2 = QtWidgets.QToolButton(self.frame_2)
        self.toolButton_2.setMinimumSize(QtCore.QSize(80, 80))
        self.toolButton_2.setMaximumSize(QtCore.QSize(80, 80))
        self.toolButton_2.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("icons/iconAgenda.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButton_2.setIcon(icon1)
        self.toolButton_2.setIconSize(QtCore.QSize(80, 80))
        self.toolButton_2.setObjectName("toolButton_2")
        self.gridLayout_6.addWidget(self.toolButton_2, 1, 3, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_9.sizePolicy().hasHeightForWidth())
        self.label_9.setSizePolicy(sizePolicy)
        self.label_9.setObjectName("label_9")
        self.gridLayout_6.addWidget(self.label_9, 3, 5, 1, 1, QtCore.Qt.AlignHCenter)
        spacerItem11 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_6.addItem(spacerItem11, 1, 6, 1, 1)
        self.toolButton_8 = QtWidgets.QToolButton(self.frame_2)
        self.toolButton_8.setMinimumSize(QtCore.QSize(80, 80))
        self.toolButton_8.setMaximumSize(QtCore.QSize(80, 80))
        self.toolButton_8.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("icons/iconsSaturno.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButton_8.setIcon(icon2)
        self.toolButton_8.setIconSize(QtCore.QSize(65, 65))
        self.toolButton_8.setObjectName("toolButton_8")
        self.gridLayout_6.addWidget(self.toolButton_8, 1, 5, 1, 1)
        spacerItem12 = QtWidgets.QSpacerItem(20, 29, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout_6.addItem(spacerItem12, 2, 5, 1, 1)
        spacerItem13 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_6.addItem(spacerItem13, 1, 4, 1, 1)
        spacerItem14 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_6.addItem(spacerItem14, 0, 5, 1, 1)
        self.gridLayout_3.addWidget(self.frame_2, 0, 1, 1, 1)
        self.frame_5 = QtWidgets.QFrame(self.frame_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_5.sizePolicy().hasHeightForWidth())
        self.frame_5.setSizePolicy(sizePolicy)
        self.frame_5.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.frame_5)
        self.gridLayout_5.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_5.setSpacing(0)
        self.gridLayout_5.setObjectName("gridLayout_5")
        spacerItem15 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_5.addItem(spacerItem15, 1, 10, 1, 1)
        spacerItem16 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_5.addItem(spacerItem16, 1, 12, 1, 1)
        spacerItem17 = QtWidgets.QSpacerItem(0, 0, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_5.addItem(spacerItem17, 1, 13, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.frame_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_7.sizePolicy().hasHeightForWidth())
        self.label_7.setSizePolicy(sizePolicy)
        self.label_7.setObjectName("label_7")
        self.gridLayout_5.addWidget(self.label_7, 3, 11, 1, 1, QtCore.Qt.AlignHCenter)
        self.BTN_CHAMADA = QtWidgets.QToolButton(self.frame_5)
        self.BTN_CHAMADA.setMinimumSize(QtCore.QSize(80, 80))
        self.BTN_CHAMADA.setMaximumSize(QtCore.QSize(80, 80))
        self.BTN_CHAMADA.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("icons/iconConciliacao.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.BTN_CHAMADA.setIcon(icon3)
        self.BTN_CHAMADA.setIconSize(QtCore.QSize(70, 70))
        self.BTN_CHAMADA.setObjectName("BTN_CHAMADA")
        self.gridLayout_5.addWidget(self.BTN_CHAMADA, 1, 8, 1, 1, QtCore.Qt.AlignHCenter)
        spacerItem18 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_5.addItem(spacerItem18, 1, 15, 1, 1)
        spacerItem19 = QtWidgets.QSpacerItem(0, 0, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_5.addItem(spacerItem19, 1, 9, 1, 1)
        spacerItem20 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_5.addItem(spacerItem20, 1, 4, 1, 1)
        self.toolButton = QtWidgets.QToolButton(self.frame_5)
        self.toolButton.setMinimumSize(QtCore.QSize(80, 80))
        self.toolButton.setMaximumSize(QtCore.QSize(80, 80))
        self.toolButton.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("icons/iconCampo.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButton.setIcon(icon4)
        self.toolButton.setIconSize(QtCore.QSize(95, 95))
        self.toolButton.setObjectName("toolButton")
        self.gridLayout_5.addWidget(self.toolButton, 1, 14, 1, 1)
        self.BTN_TEMPLO = QtWidgets.QToolButton(self.frame_5)
        self.BTN_TEMPLO.setMinimumSize(QtCore.QSize(80, 80))
        self.BTN_TEMPLO.setMaximumSize(QtCore.QSize(80, 80))
        self.BTN_TEMPLO.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("icons/iconIgreja.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.BTN_TEMPLO.setIcon(icon5)
        self.BTN_TEMPLO.setIconSize(QtCore.QSize(70, 70))
        self.BTN_TEMPLO.setObjectName("BTN_TEMPLO")
        self.gridLayout_5.addWidget(self.BTN_TEMPLO, 1, 16, 1, 1, QtCore.Qt.AlignTop)
        self.label_3 = QtWidgets.QLabel(self.frame_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        self.label_3.setObjectName("label_3")
        self.gridLayout_5.addWidget(self.label_3, 3, 2, 1, 1, QtCore.Qt.AlignHCenter)
        self.BTN_GRAFICO_DE_PRESENCA = QtWidgets.QToolButton(self.frame_5)
        self.BTN_GRAFICO_DE_PRESENCA.setMinimumSize(QtCore.QSize(80, 80))
        self.BTN_GRAFICO_DE_PRESENCA.setMaximumSize(QtCore.QSize(80, 16777215))
        self.BTN_GRAFICO_DE_PRESENCA.setText("")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap("icons/grafico.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.BTN_GRAFICO_DE_PRESENCA.setIcon(icon6)
        self.BTN_GRAFICO_DE_PRESENCA.setIconSize(QtCore.QSize(60, 65))
        self.BTN_GRAFICO_DE_PRESENCA.setObjectName("BTN_GRAFICO_DE_PRESENCA")
        self.gridLayout_5.addWidget(self.BTN_GRAFICO_DE_PRESENCA, 1, 11, 1, 1, QtCore.Qt.AlignHCenter)
        self.BTN_BUSCAR_MEMBRO = QtWidgets.QToolButton(self.frame_5)
        self.BTN_BUSCAR_MEMBRO.setMinimumSize(QtCore.QSize(80, 80))
        self.BTN_BUSCAR_MEMBRO.setMaximumSize(QtCore.QSize(80, 80))
        self.BTN_BUSCAR_MEMBRO.setText("")
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap("icons/iconClientes.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.BTN_BUSCAR_MEMBRO.setIcon(icon7)
        self.BTN_BUSCAR_MEMBRO.setIconSize(QtCore.QSize(80, 80))
        self.BTN_BUSCAR_MEMBRO.setObjectName("BTN_BUSCAR_MEMBRO")
        self.gridLayout_5.addWidget(self.BTN_BUSCAR_MEMBRO, 1, 2, 1, 1)
        spacerItem21 = QtWidgets.QSpacerItem(8, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_5.addItem(spacerItem21, 1, 3, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.frame_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_5.sizePolicy().hasHeightForWidth())
        self.label_5.setSizePolicy(sizePolicy)
        self.label_5.setObjectName("label_5")
        self.gridLayout_5.addWidget(self.label_5, 3, 14, 1, 1, QtCore.Qt.AlignHCenter)
        self.label_6 = QtWidgets.QLabel(self.frame_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_6.sizePolicy().hasHeightForWidth())
        self.label_6.setSizePolicy(sizePolicy)
        self.label_6.setObjectName("label_6")
        self.gridLayout_5.addWidget(self.label_6, 3, 16, 1, 1, QtCore.Qt.AlignHCenter)
        spacerItem22 = QtWidgets.QSpacerItem(20, 48, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout_5.addItem(spacerItem22, 2, 11, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.frame_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_8.sizePolicy().hasHeightForWidth())
        self.label_8.setSizePolicy(sizePolicy)
        self.label_8.setObjectName("label_8")
        self.gridLayout_5.addWidget(self.label_8, 3, 8, 1, 1, QtCore.Qt.AlignHCenter)
        spacerItem23 = QtWidgets.QSpacerItem(20, 48, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout_5.addItem(spacerItem23, 4, 11, 1, 1)
        spacerItem24 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_5.addItem(spacerItem24, 1, 17, 1, 1)
        spacerItem25 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_5.addItem(spacerItem25, 1, 1, 1, 1)
        spacerItem26 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_5.addItem(spacerItem26, 0, 11, 1, 1)
        self.gridLayout_3.addWidget(self.frame_5, 0, 0, 1, 1)
        self.gridLayout_2.addWidget(self.frame_4, 1, 1, 1, 2, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.frame_8 = QtWidgets.QFrame(self.frame)
        self.frame_8.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_8.setObjectName("frame_8")
        self.gridLayout_2.addWidget(self.frame_8, 0, 0, 3, 1)
        self.frame_9 = QtWidgets.QFrame(self.frame)
        self.frame_9.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_9.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_9.setObjectName("frame_9")
        self.gridLayout_2.addWidget(self.frame_9, 1, 3, 2, 1)
        self.frame_7 = QtWidgets.QFrame(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_7.sizePolicy().hasHeightForWidth())
        self.frame_7.setSizePolicy(sizePolicy)
        self.frame_7.setMinimumSize(QtCore.QSize(30, 30))
        self.frame_7.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.frame_7)
        self.gridLayout_4.setContentsMargins(0, 3, 4, 0)
        self.gridLayout_4.setVerticalSpacing(0)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.BTN_MAXIMIZAR = QtWidgets.QToolButton(self.frame_7)
        self.BTN_MAXIMIZAR.setMinimumSize(QtCore.QSize(29, 29))
        self.BTN_MAXIMIZAR.setMaximumSize(QtCore.QSize(29, 29))
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap("icons/Maximize.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.BTN_MAXIMIZAR.setIcon(icon8)
        self.BTN_MAXIMIZAR.setIconSize(QtCore.QSize(25, 25))
        self.BTN_MAXIMIZAR.setObjectName("BTN_MAXIMIZAR")
        self.gridLayout_4.addWidget(self.BTN_MAXIMIZAR, 0, 2, 1, 1)
        self.BTN_MINIMIZAR = QtWidgets.QToolButton(self.frame_7)
        self.BTN_MINIMIZAR.setMinimumSize(QtCore.QSize(29, 29))
        self.BTN_MINIMIZAR.setMaximumSize(QtCore.QSize(29, 29))
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap("icons/Minimize.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.BTN_MINIMIZAR.setIcon(icon9)
        self.BTN_MINIMIZAR.setIconSize(QtCore.QSize(25, 25))
        self.BTN_MINIMIZAR.setObjectName("BTN_MINIMIZAR")
        self.gridLayout_4.addWidget(self.BTN_MINIMIZAR, 0, 1, 1, 1)
        spacerItem27 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_4.addItem(spacerItem27, 1, 3, 1, 1)
        self.BTN_FECHAR = QtWidgets.QToolButton(self.frame_7)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.BTN_FECHAR.sizePolicy().hasHeightForWidth())
        self.BTN_FECHAR.setSizePolicy(sizePolicy)
        self.BTN_FECHAR.setMinimumSize(QtCore.QSize(28, 28))
        self.BTN_FECHAR.setMaximumSize(QtCore.QSize(29, 29))
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap("icons/Exit.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.BTN_FECHAR.setIcon(icon10)
        self.BTN_FECHAR.setIconSize(QtCore.QSize(25, 25))
        self.BTN_FECHAR.setObjectName("BTN_FECHAR")
        self.gridLayout_4.addWidget(self.BTN_FECHAR, 0, 3, 1, 1)
        spacerItem28 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem28, 0, 0, 1, 1)
        self.gridLayout_2.addWidget(self.frame_7, 0, 1, 1, 3)
        spacerItem29 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem29, 2, 1, 1, 2)
        self.gridLayout.addWidget(self.frame, 0, 0, 1, 1)
        telaPrincipal.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(telaPrincipal)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 908, 21))
        self.menubar.setObjectName("menubar")
        self.menuMENU = QtWidgets.QMenu(self.menubar)
        self.menuMENU.setObjectName("menuMENU")
        self.menuFERRAMENTAS = QtWidgets.QMenu(self.menubar)
        self.menuFERRAMENTAS.setObjectName("menuFERRAMENTAS")
        self.menuCONFIGURACOES = QtWidgets.QMenu(self.menubar)
        self.menuCONFIGURACOES.setObjectName("menuCONFIGURACOES")
        self.menuAJUDA = QtWidgets.QMenu(self.menubar)
        self.menuAJUDA.setObjectName("menuAJUDA")
        telaPrincipal.setMenuBar(self.menubar)
        self.actionLOGIN = QtWidgets.QAction(telaPrincipal)
        self.actionLOGIN.setObjectName("actionLOGIN")
        self.actionREGISTRO = QtWidgets.QAction(telaPrincipal)
        self.actionREGISTRO.setObjectName("actionREGISTRO")
        self.actionATIVACAO = QtWidgets.QAction(telaPrincipal)
        self.actionATIVACAO.setObjectName("actionATIVACAO")
        self.actionGRAFICOS = QtWidgets.QAction(telaPrincipal)
        self.actionGRAFICOS.setObjectName("actionGRAFICOS")
        self.actionCHAMADA = QtWidgets.QAction(telaPrincipal)
        self.actionCHAMADA.setObjectName("actionCHAMADA")
        self.menuMENU.addAction(self.actionLOGIN)
        self.menuMENU.addAction(self.actionREGISTRO)
        self.menuMENU.addAction(self.actionATIVACAO)
        self.menuFERRAMENTAS.addAction(self.actionGRAFICOS)
        self.menuFERRAMENTAS.addAction(self.actionCHAMADA)
        self.menubar.addAction(self.menuMENU.menuAction())
        self.menubar.addAction(self.menuFERRAMENTAS.menuAction())
        self.menubar.addAction(self.menuCONFIGURACOES.menuAction())
        self.menubar.addAction(self.menuAJUDA.menuAction())

        self.retranslateUi(telaPrincipal)
        self.BTN_FECHAR.clicked.connect(telaPrincipal.close) # type: ignore
        self.BTN_MAXIMIZAR.clicked.connect(telaPrincipal.showMaximized) # type: ignore
        self.BTN_MINIMIZAR.clicked.connect(telaPrincipal.showNormal) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(telaPrincipal)

    def retranslateUi(self, telaPrincipal):
        _translate = QtCore.QCoreApplication.translate
        telaPrincipal.setWindowTitle(_translate("telaPrincipal", "ATAS DE REUNIÃO"))
        self.label.setText(_translate("telaPrincipal", "Gerar Relatório"))
        self.label_4.setText(_translate("telaPrincipal", "Agenda"))
        self.label_9.setText(_translate("telaPrincipal", "<html><head/><body><p align=\"center\">Alinhamentos</p><p align=\"center\">Planetários</p></body></html>"))
        self.label_7.setText(_translate("telaPrincipal", "Gráficos de Presença"))
        self.label_3.setText(_translate("telaPrincipal", "Membros"))
        self.label_5.setText(_translate("telaPrincipal", "Campos"))
        self.label_6.setText(_translate("telaPrincipal", "Templos"))
        self.label_8.setText(_translate("telaPrincipal", "Chamada"))
        self.BTN_MAXIMIZAR.setText(_translate("telaPrincipal", "..."))
        self.BTN_MINIMIZAR.setText(_translate("telaPrincipal", "..."))
        self.BTN_FECHAR.setText(_translate("telaPrincipal", "..."))
        self.menuMENU.setTitle(_translate("telaPrincipal", "MENU"))
        self.menuFERRAMENTAS.setTitle(_translate("telaPrincipal", "FERRAMENTAS"))
        self.menuCONFIGURACOES.setTitle(_translate("telaPrincipal", "CONFIGURAÇÕES"))
        self.menuAJUDA.setTitle(_translate("telaPrincipal", "AJUDA"))
        self.actionLOGIN.setText(_translate("telaPrincipal", "LOGIN"))
        self.actionREGISTRO.setText(_translate("telaPrincipal", "REGISTRO"))
        self.actionATIVACAO.setText(_translate("telaPrincipal", "ATIVAÇÃO"))
        self.actionGRAFICOS.setText(_translate("telaPrincipal", "GRÁFICOS"))
        self.actionCHAMADA.setText(_translate("telaPrincipal", "CHAMADA"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    telaPrincipal = QtWidgets.QMainWindow()
    ui = Ui_telaPrincipal()
    ui.setupUi(telaPrincipal)
    telaPrincipal.show()
    sys.exit(app.exec_())
